; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s

@gd = external global i16

define i32 @test_load_and_cmp(i32 %a, i32 %b, i16 %c) nounwind {
; RV64I-LABEL: test_load_and_cmp:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a0, %hi(gd)
; RV64I-NEXT:    lh a0, %lo(gd)(a0)
; RV64I-NEXT:    add a0, a2, a0
; RV64I-NEXT:    ret
  %q = add i32 %a, %b
  ret i32 %q;
}

