; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64  -mattr=+xtheadba -mattr=+xtheadbb -mattr=+xtheadbs \
; RUN: | FileCheck %s -check-prefix=THEADBB



declare i64 @llvm.riscv.tstnbz.i64(i64 %a)

define i64 @tstnbz_dw(i64 %a) nounwind {
; THEADBB-LABEL: tstnbz_dw:
; THEADBB:       # %bb.0:
; THEADBB-NEXT:    tstnbz a0, a0
; THEADBB-NEXT:    ret
  %tmp = call i64 @llvm.riscv.tstnbz.i64(i64 %a)
  ret i64 %tmp
}
