; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64I %s

define i32 @test_load_and_cmp(i32 %a, i32 %b) nounwind {
  %xored = xor i32 %a, %b
  %sexted = sext i32 %xored to i64
  %muled = mul nuw nsw %sexted, 7
  return %muled;
}

