; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -mtriple=riscv64 | FileCheck %s


define i32 @test_load_and_cmp(i16 %a, i16 %k) nounwind {
  %q = xor i16 %a, %k
  %sexted_q = sext i16 %q to i32
  %res = add i32 %sexted_q, 10
  ret i32 %res;
}

