; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

@gd = external global i16

define i32 @foo(i16 %a, i16 %b) nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    leal (%rdi,%rsi), %eax
; CHECK-NEXT:    retq
  %k = load i16, ptr @gd
  %q = xor i16 %a, %k
  %sexted_q = sext i16 %q to i32
  %res = add i32 %sexted_q, 10
  ret i32 %res;
}
